import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] });
import Providers from './providers';
import Header from '@/components/main/header';
import Footer from '@/components/main/footer';
export const metadata: Metadata = {
  title: 'Foodluk',
  description: 'Generated by Foodluk',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
      <body className={inter.className}>
        <div className="overflow-hidden">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
