import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import '../globals.css';
const inter = Inter({ subsets: ['latin'] });
import Header from '@/components/main/header';
import Footer from '@/components/main/footer';
import Providers from '../providers';
export const metadata: Metadata = {
  title: 'Restaurant SAAS',
  description: 'Generated by Arya',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <Header />
      <main className="flex flex-col min-h-screen">{children}</main>
      <Footer />
    </Providers>
  );
}
